Added more tools and README.md comments about running test coverage. (#5)
* Added more tools and README.md comments about running test coverage.

* Cleaned up mod and sum.

* [bumpver] 0.2.1

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,7 +1,7 @@
 name: Tests
 
 #
-# Run unit tests
+# Run unit tests and fail if coverage is below threshold
 #
 
 on:
@@ -30,6 +30,11 @@ jobs:
         run: |
           go mod tidy
 
-      - name: Unit tests
+      - name: Run tests and check coverage
         run: |
-          go test ./...
+          go test -v -coverprofile=coverage.out ./...
+          COVERAGE=$(go tool cover -func=coverage.out | sed -n '/total/p' | awk '{print substr($NF, 1, length($NF)-1)}')
+          if (( $(echo "$COVERAGE < 90" | bc -l) )); then
+              echo "Coverage is below 90%: $COVERAGE%"
+              exit 1
+          fi
